apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
data:
  #used with env variables in deployment.yml to set properties using secrets
  username: dXNlcm5hbWUoc2VjcmV0cy9kYXRhKQ== # base64(username(secrets/data))
  secret: c2VjcmV0KHNlY3JldHMvZGF0YSk= # base64(secret(secrets/data))
stringData:
  secret.properties: |-
    username=username(secrets/secret.properties)
    secret=secret(secrets/secret.properties)
